# Create class architecture

# Admin users are a kind of users
tim = AdminUser("tim")
sheila = AdminUser("sheila")
# Customers users have a balance, and they can buy products if they have enough balance
karen = CustomerUser("karen", 100) # first arg is name, second is balance
julio = CustomerUser("julio", 25)
# Moderators users moderates forums on the website (not relevant to current workshop)
vince = ModeratorUser("vince", {"flowers", "general"})
kim = ModeratorUser("vince", {"general", "FAQ"})

# Products can be bought, they just hold a value - see user.can_buy(product)
product1 = Product(40) # first arg is price

users = [tim, sheila, karen, julio, vince, kim]

for user in users:
    print(str(user) + " - " + user.can_buy(product1))

# user should have a nice string representation, which include an id (autogenerated, incrementing)
assert str(sheila) == "#2 sheila" # format is #{id} {name}
assert str(kim) == "#6 kim"
